config/routes.rb
Harmony::Application.routes.draw do

  match '/access_denied' => 'error#access_denied', :as => :access_denied
  match '/not_found' => 'error#not_found', :as => :not_found

  match '/language/:lang_cut' => 'welcome#set_lang', :as => :lang_switch

  scope '/:locale', :locale => /en|ru/ do

    get '/conception' => 'statics#idea', :as => :idea
    get '/person' => 'statics#person', :as => :person
    resources :posts
    resources :statics

  end

  root :to => 'welcome#index'

end

app/models/language.rb
#encoding: utf-8
class Language
  attr_accessor :name
  attr_accessor :cut

  def self.collection(with_all_regions = false)
    list = [
        Language.new(:name => 'En', :cut => 'en'),
        Language.new(:name => 'Ru', :cut => 'ru')
    ]
    list = [Language.new(:name => 'All regions', :cut => '')] + list if with_all_regions
    list
  end

  def self.include?(lang_cut)
    collection.each do |lang|
      return true if lang.cut == lang_cut
    end
    false
  end

  def initialize(hash)
    self.name = hash[:name]
    self.cut = hash[:cut]
  end

end

app/models/not_found.rb
class NotFound < Exception
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :lang, :short, :title
end

app/models/static.rb
class Static < ActiveRecord::Base
  attr_accessible :body_en, :body_ru, :short_en, :short_ru, :title_en, :title_ru, :short_url

  def title
    send "title_#{I18n.locale}"
  end

  def short
    send "short_#{I18n.locale}"
  end

  def body
    send "body_#{I18n.locale}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_locale

  rescue_from NotFound, :with => :not_found
  rescue_from ActiveRecord::RecordNotFound, :with => :not_found

  def default_url_options(options={})
    logger.debug "default_url_options is passed options: #{options.inspect}\n"
    {locale: I18n.locale}
  end

  protected

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end


  private


  def access_denied
    redirect_to access_denied_path
  end

  def not_found
    redirect_to not_found_path
  end


end

app/controllers/error_controller.rb
class ErrorController < ApplicationController

  def access_denied
    render :action => 'access_denied', :status => 403
  end

  def not_found
    render :action => 'not_found', :status => 404
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @page = :publications
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController

  def idea
    @page = :idea
    @static = Static.find_by_short_url("conception")
    render :show
  end

  def person
    @page = :person
    @static = Static.find_by_short_url("person")
    render :show
  end

  # GET /statics
  # GET /statics.json
  def index
    @statics = Static.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @statics }
    end
  end

  # GET /statics/1
  # GET /statics/1.json
  def show
    @static = Static.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @static }
    end
  end

  def new
  @static = Static.new

  respond_to do |format|
     format.html # new.html.erb
     format.json { render json: @static }
  end
  end

  def edit
  @static = Static.find(params[:id])
  end

  def create
  @static = Static.new(params[:static])

  respond_to do |format|
     if @static.save
       format.html { redirect_to @static, notice: 'Static was successfully created.' }
       format.json { render json: @static, status: :created, location: @static }
     else
       format.html { render action: "new" }
       format.json { render json: @static.errors, status: :unprocessable_entity }
     end
  end
  end

  def update
  @static = Static.find(params[:id])

  respond_to do |format|
     if @static.update_attributes(params[:static])
       format.html { redirect_to @static, notice: 'Static was successfully updated.' }
       format.json { head :no_content }
     else
       format.html { render action: "edit" }
       format.json { render json: @static.errors, status: :unprocessable_entity }
     end
  end
  end

  def destroy
  @static = Static.find(params[:id])
  @static.destroy

  respond_to do |format|
     format.html { redirect_to statics_url }
     format.json { head :no_content }
  end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def set_lang
    #raise NotFound unless [:en, :ru].include?(params[:lang_cut])
    redirect_to "/?locale=#{params[:lang_cut]}"
  end

  def index
    @page = :welcome
    @banner = Static.find_by_short_url("book-release")
    @posts = Post.where(:lang => I18n.locale).order("ID DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(target)
    #content_for(:title) { target.seo_data.nil? ? target.title || t('title') : target.seo_data.title }
  end

  def seo_data(target)
    #if target.seo_data.nil?
    #  content_for(:description) { t('description') }
    #  content_for(:keywords) { t('keywords') }
    #else
    #  content_for(:description) { target.seo_data.description.nil? ? t('description') : target.seo_data.description }
    #  content_for(:keywords) { target.seo_data.keywords.nil? ? t('keywords') : target.seo_data.keywords.gsub('"', '\"') }
    #end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_banner.html.erb
<%= raw @banner.body %>

app/views/layouts/_header.html.erb
<div class="header">

  <div id="menu">
    <ul>
      <li class='<%= :active if @page == :publications %>'><%= link_to t('main_menu.posts'), root_path %></li>
      <li class='<%= :active if @page == :idea %>'><%= link_to t('main_menu.idea'), idea_path %></li>
      <li class='<%= :active if @page == :person %>'><%= link_to t('main_menu.person'), person_path %></li>
    </ul>
  </div>

  <%= render "layouts/lang_switch" %>

</div>

app/views/layouts/_lang_switch.html.erb
<div id="lang">
  <% Language.collection.each do |lang| %>
      <%= link_to lang.name.upcase, lang_switch_path(lang.cut) unless I18n.locale.to_s == lang.cut %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title><%= t('site_title') %></title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="keywords" content="Иосиф Шевелев, Шевелев, Иосиф Шефтелевич Шевелев, Joseph Shevelev, Архитектура, Золотое сечение, Гармония, Harmony, Golden section, Гармония в зеркале геометрии, Harmony in a mirror of geometry">
  <meta name="description" content="Пропорции, форма, образ, структура. Шедевры зодчества: Парфенон. Целостность и комбинаторика. Парные меры и архитектура Древней Руси. Proportions, the form, image, structure. Architecture masterpieces: Parthenon. Integrity & combinatorial analysis. Conjugate measures and architecture of Ancient Russia.">
</head>
<body>

<div class="header-container">
  <%= render "layouts/header" %>
  <%= render "layouts/banner" if @page == :welcome %>
</div>

<div class="content-container <%= 'with-banner' if @page == :welcome %>">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :lang %>
      <%= f.collection_select(:lang, Language.collection, :cut, :name, :value => I18n.locale, :prompt => false) %>
    </div>
    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :short %>
      <%= f.text_area :short, :class => "short" %>
    </div>
    <div class="field">
      <%= f.label :body %>
      <%= f.text_area :body, :class => "full" %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/posts/edit.html.erb
<div class="content">
  <h1>Изменение публикации</h1>
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Lang</th>
    <th>Title</th>
    <th>Short</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.lang %></td>
    <td><%= post.title %></td>
    <td><%= post.short %></td>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<div class="content">
  <h1>Создание публикации</h1>
  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="content">
  <%= content_tag :h1, @post.title %>


  <div id="slides">
    <ul>
    <%= content_tag :li, image_tag("picts/1.jpg") %>
    <%= content_tag :li, image_tag("picts/3.jpg") %>
    <%= content_tag :li, image_tag("picts/4.jpg") %>
    <%= content_tag :li, image_tag("picts/9.jpg") %>
    <%= content_tag :li, image_tag("picts/10.jpg") %>
    <%= content_tag :li, image_tag("picts/15.jpg") %>
    <%= content_tag :li, image_tag("picts/28.jpg") %>
    <%= content_tag :li, image_tag("picts/29.jpg") %>
    <%= content_tag :li, image_tag("picts/33.jpg") %>
    <%= content_tag :li, image_tag("picts/36.jpg") %>
    <%= content_tag :li, image_tag("picts/42-a.jpg") %>
    <%= content_tag :li, image_tag("picts/42-b.jpg") %>
    </ul>

    <script type="text/javascript">
        $('#slides').sudoSlider({});
    </script>
  </div>

  <p class="short">
    <%= @post.short %>
  </p>

  <div class="post">
    <%= raw @post.body %>
  </div>
</div>

app/views/statics/_form.html.erb
<%= form_for(@static) do |f| %>
    <% if @static.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@static.errors.count, "error") %> prohibited this static from being saved:</h2>

          <ul>
            <% @static.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title_ru %>
      <%= f.text_field :title_ru %>
    </div>
    <div class="field">
      <%= f.label :title_en %>
      <%= f.text_field :title_en %>
    </div>
    <div class="field">
      <%= f.label :short_ru %>
      <%= f.text_area :short_ru, :class => "short" %>
    </div>
    <div class="field">
      <%= f.label :short_en %>
      <%= f.text_area :short_en, :class => "short" %>
    </div>
    <div class="field">
      <%= f.label :body_ru %>
      <%= f.text_area :body_ru, :class => "full" %>
    </div>
    <div class="field">
      <%= f.label :body_en %>
      <%= f.text_area :body_en, :class => "full" %>
    </div>
    <div class="field">
      <%= f.label :short_url %>
      <%= f.text_field :short_url %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/statics/edit.html.erb
<div class="content">
  <h1>Изменение раздела</h1>
  <%= render 'form' %>
</div>

app/views/statics/index.html.erb
<h1>Listing statics</h1>

<table>
  <tr>
    <th>Title en</th>
    <th>Title ru</th>
    <th>Short en</th>
    <th>Short ru</th>
    <th>Body en</th>
    <th>Body ru</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @statics.each do |static| %>
  <tr>
    <td><%= static.title_en %></td>
    <td><%= static.title_ru %></td>
    <td><%= static.short_en %></td>
    <td><%= static.short_ru %></td>
    <td><%= static.body_en %></td>
    <td><%= static.body_ru %></td>
    <td><%= link_to 'Show', static %></td>
    <td><%= link_to 'Edit', edit_static_path(static) %></td>
    <td><%= link_to 'Destroy', static, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Static', new_static_path %>

app/views/statics/new.html.erb
<div class="content">
  <h1>Создание раздела</h1>
  <%= render 'form' %>
</div>

app/views/statics/show.html.erb
<%#= link_to 'Edit', edit_static_path(@static) %>

<%= raw @static.body %>

app/views/welcome/index.html.erb
<% unless @posts.empty? %>
    <% @posts.each do |post| %>
        <% if cycle('odd', 'even') == 'odd' %>
            <div class="content-full-width-container">
              <div class="content">
                <img src="/assets/picts/harmony-mirror.jpg" class="image-circle anounce-list" alt="Персона">

                <div class="text-right">
                  <%= content_tag :h2, link_to(post.title, post) %>
                  <%= content_tag :p, post.short %>
                </div>
              </div>
            </div>
        <% else %>
            <div class="content">
              <img src="/assets/picts/alphaomega.jpg" class="image-circle anounce-list" alt="Персона">

              <div class="text-right">
                <%= content_tag :h2, link_to(post.title, post) %>
                <%= content_tag :p, post.short %>
              </div>
            </div>
        <% end %>
    <% end %>
<% else %>
    <div class="content">
        <%= content_tag :h2, t("welcome.no_posts") %>
    </div>
<% end %>